# Generated by Django 4.2.2 on 2023-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('souceURL', models.TextField()),
                ('newsContent', models.TextField()),
            ],
        ),
    ]
